language: node_js
node_js:
- 10.14.1
after_success: "./node_modules/.bin/codecov"
deploy:
  provider: npm
  on:
    tags: true
    repo: parse-community/parse-server-push-adapter
  api_key:
    secure: VBk+o3Si1MAe8KJ8qSveEsvKU/g4byTs6IO3og5FZSCNFLsn2HaIn12KFE/YTGbygTv1wusOf4qnKG/ag0VNaVaSZ7gIddYVCPw94k0M4Ig3r+FkUR+zHvx5VEWg3YVUSvC+j5lLUqcHXo4r0vbPWNLNcGjKcOsbSEC61T4juskkEC9lTmRaOCRBcZtI5DZ4iLzc+YqFToRL7YWm8i9MY9mB4oLcg/GO460wGuB5hKHPEsruy4dbYIezaUtxqpikZ1spQzzqSUrFFJLQoEcJdTraLBi1rRVb4P7kUErtq0ZUzBdqwAbwz+iowfyYWAONQqK45t1lD6x4vG2M4ps4UW7eMsRkFZakPafGZwIg24LIsHIH3V4qkcP0gc/AiKKXEluql/9bdcwDvBmy5439xSaid46QzcyPjrn7qTxjmwDlBJ1vPuJpADuUCDBc2H9KWOjpHNYPcOEInysjelXadzRFQqR51rOEK/nlYZEeUQLPGvNbntP+r0qcVNXyoDCvxDiq/aQdgJgdG0te5Smd/9cOwDOZxK9Z8lGJ1pWldJ0Da6YgdrJ9ui04GQdNlTb2vyFOsd6YIOgwQIWoSXFdOtkmDf+ozkEmDdu1p4ReezmBK7DIhBJ1X18HkaiNrZcc956UDYYsoI4fY+dwrS8bWzMg9GgjXcA/ldQh6hhdUXg=
  email:
    secure: HxWGX+GGmxx1b8qp/s1g4s0dm15Qthf55Peh+Fgi+JNWzQFkUVDAEeUs7e1DTxubcGhUiE8QI/edQbcw6JeMQf+8cnAfqTzTZI7Au/Kgrn5vQR8BLkE1rYZD1vtfHtZ7sl8ZDui1jclOxG6V5ZqUCDKCyaKW0Quq4qROyumuluMCJ+Ds2Za2xBO9StsrrQleAvhReOd7IiZVokZVidKxhynUxHHPdX/FgG7C8HsaWFDFd9jPLvRylB2AVr/BB2gZqS+D76EJIc4fLervMD4UDRML5mwBmlrfH1EgS/9NGv66iLhisKgDLeh5TT+lMMPJihWvUk2K42c9HfRNJHozGDJZt77EuOEg+zkYRSSomEBY0a0zoDtiZHfwDjZ9jfbLua0DfD7sD3d3DAbkTdYkz9e5TMGdP7lVNg8+LtzCTZQnuOs7VHCE7LxLhS8AjaqvrA2LSxEU64U1HBIrcy1vxx7ipLMZa9HO+GmmznsDd5nZJ9ukSIGTyWzHMR6n7jhs7+q5QKlxeS9icNBrU5hRSYjfm19hCV+A1X1EDUSKQ79yIqO68F+d09vQuHigQFHpaDCr+ya79qpDogbIoI5fE5T4plXKsK2q2mPsK5OIPadr3h0rSPBL1UUIdP9Hzn2FOXtpFv0n7NcmHbz8cRPf5oB1Q1tQFA5VDYEW6EE4YIk=
